vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        illustration_file:
            uri_prefix: /public/uploads/Illustration/photos
            upload_destination: '%kernel.project_dir%/public/uploads/Illustration/photos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


