<?php

namespace ContainerM991Ehg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GeGPzKiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.geGPzKi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.geGPzKi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cart' => ['privates', 'App\\Class\\Cart', 'getCartService', true],
        ], [
            'cart' => 'App\\Class\\Cart',
        ]);
    }
}
