<?php

namespace ContainerM991Ehg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarteControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CarteController' shared autowired service.
     *
     * @return \App\Controller\CarteController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CarteController.php';

        $container->services['App\\Controller\\CarteController'] = $instance = new \App\Controller\CarteController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\CarteController', $container));

        return $instance;
    }
}
